#!/usr/bin/env bash

DEFAULT_TIMEZONE="Asia/Tehran"
DEFAULT_N8N_IMAGE="n8nio/n8n:latest"
DEFAULT_KUMA_IMAGE="louislam/uptime-kuma:2"
DEFAULT_NGINX_IMAGE="nginx:1.28.0-alpine"
DEFAULT_RETENTION_DAYS="14"
DEFAULT_KUMA_PORT="3001"

validate_domain() {
    local domain="$1" label

    [[ ${#domain} -le 253 ]] || return 1
    [[ "$domain" == *.* ]] || return 1
    [[ "$domain" =~ ^[A-Za-z0-9.-]+$ ]] || return 1
    [[ "$domain" != .* && "$domain" != *. && "$domain" != *..* ]] || return 1

    IFS='.' read -r -a labels <<< "$domain"
    for label in "${labels[@]}"; do
        [[ ${#label} -ge 1 && ${#label} -le 63 ]] || return 1
        [[ "$label" =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?$ ]] || return 1
    done
}

prompt_with_default() {
    local prompt="$1" default="$2" value
    read -r -p "${prompt} [${default}]: " value
    printf '%s' "${value:-$default}"
}

core_prompt() {
    while :; do
        read -r -p "Full n8n domain (for example automation.example.com): " N8N_HOST
        N8N_HOST="${N8N_HOST,,}"
        validate_domain "$N8N_HOST" && break
        warn "Enter a DNS hostname with at least two valid labels."
    done

    while :; do
        TIMEZONE="$(prompt_with_default "Timezone" "$DEFAULT_TIMEZONE")"
        if [[ "$TIMEZONE" =~ ^[A-Za-z0-9_+.-]+(/[A-Za-z0-9_+.-]+)*$ && "$TIMEZONE" != *..* && -f "/usr/share/zoneinfo/${TIMEZONE}" ]]; then
            break
        fi
        warn "Timezone not found under /usr/share/zoneinfo."
    done

    while :; do
        N8N_IMAGE="$(prompt_with_default "n8n image" "$DEFAULT_N8N_IMAGE")"
        [[ "$N8N_IMAGE" =~ ^[A-Za-z0-9._/:@-]+$ ]] && break
        warn "Image reference contains unsupported characters."
    done

    while :; do
        BACKUP_RETENTION_DAYS="$(prompt_with_default "Local backup retention in days" "$DEFAULT_RETENTION_DAYS")"
        [[ "$BACKUP_RETENTION_DAYS" =~ ^[0-9]+$ ]] && break
        warn "Retention must be a non-negative whole number."
    done

    KUMA_IMAGE="$DEFAULT_KUMA_IMAGE"
    NGINX_IMAGE="$DEFAULT_NGINX_IMAGE"
    KUMA_PORT="$DEFAULT_KUMA_PORT"
}

core_write_env() {
    local env_tmp
    env_tmp="$(mktemp "${PROJECT_DIR}/.env.tmp.XXXXXX")"

    cat > "$env_tmp" <<EOF
# Generated by install.sh. Re-run the installer or edit with care.
N8N_HOST=${N8N_HOST}
TIMEZONE=${TIMEZONE}
N8N_IMAGE=${N8N_IMAGE}
KUMA_IMAGE=${KUMA_IMAGE}
NGINX_IMAGE=${NGINX_IMAGE}
KUMA_PORT=${KUMA_PORT}

TLS_ENABLED=${TLS_ENABLED}
LETSENCRYPT_PATH=${LETSENCRYPT_PATH}
TLS_CERT_NAME=${TLS_CERT_NAME}
TLS_VOLUME_SOURCE=${TLS_VOLUME_SOURCE}
PUBLIC_SCHEME=${PUBLIC_SCHEME}
NGINX_TLS_PREFIX="${NGINX_TLS_PREFIX}"
NGINX_HTTP_PREFIX="${NGINX_HTTP_PREFIX}"

BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS}
EOF

    chmod 600 "$env_tmp"
    mv -f "$env_tmp" "${PROJECT_DIR}/.env"
    ok "Wrote .env with mode 600."
}
